game: "The Witcher 3: Wild Hunt"
api: 1
steamID: 292030
uid: com.thegreatcabbage.witcher3
author: TheGreatCabbage
packageName: "witcher3"
features:
  - "graphics"
  - "keymaps"
  - "saves"

graphicsConfig: $!DOCUMENTS/The Witcher 3/user.settings
keymapConfig: $!DOCUMENTS/The Witcher 3/
saves: $!DOCUMENTS/The Witcher 3/gamesaves

gameDirectory: 
  - "The Witcher 3 Wild Hunt GOTY"
  - "The Witcher 3 Wild Hunt"
verificationPaths:
  - bin/x64/witcher3.exe
